softeerbootcamp4th/be-was-2024

- src/main/java/common/WebUtils.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/WebServer.java
- uri 경로에 따라서 정적 페이지 응답
- HTTP 요청을 Logger를 통해 Debug
- ExecutorService를 통해 쓰레드풀 관리
- 유지보수에 좋은 코드 만들기
- 상대경로 미동작으로 인한 절대경로 file path 설정
> fix: 웹 서버 week1 1단계 - 기능 요구사항 반영

- README.md
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/WebServer.java
RequestHandler.java
request header를 map 형식으로 저장 및 출력
html, css, js ico, png, jpg, svg 확장자 요청에 대한 처리 완료
해당 확장자 이외의 확장자들은 405 Unsupported content type을 띄우도록 만듬
thread를 fixedthreadpool을 이용하여 관련하게 변경
reqeuset header에 대한 log를 출력하게 변경
추가적인 주석 및 task1 README.md 내용추가
> week1-task1 commit

- .idea/modules.xml
- .idea/modules/be-was-neon.test.iml
- README.md
- build.gradle
- locustfile.py
- src/main/java/webserver/FileContentReader.java
- src/main/java/webserver/HttpRequestParser.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/WebServer.java
- src/test/java/webserver/FileContentReaderTest.java
- src/test/java/webserver/HttpRequestParserTest.java
웹 서버 1단계 - index.html 응답
* Request URL 경로 추출 및 정적 파일 반환
* 기존 Thread -> Concurrent 패키지 사용
* ThreadPool 사용
* HttpRequestParser, FileContentReader 단위 테스트 코드 작성
> [FEAT] 웹 서버 1단계 - index.html 응답

- .idea/compiler.xml
- .idea/misc.xml
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/WebServer.java
- index.html 파일을 읽어 클라이언트에 응답
- HTTP Request의 내용을 읽고 적절하게 파싱해서 로거(log.debug)를 이용해 출력
- Concurrent 패키지 사용
- JDK의 nio 미사용
- Content-Type은 확장자를 통해 구분
- svg,ico 확장자에 대한 추가 처리
> 1-1, 1-2 미션 구현 및 커밋 수정 사항 변경

- src/main/java/util/HttpRequest.java
- src/main/java/util/HttpResponse.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/WebServer.java
- 기능 추가
- 의존성 관련 코드 업데이트
JongssLee/de-was-2024:feature1 -> JongssLee
- 정적 html 파일 응답
- http://localhost:8080/index.html 로 접속했을 때 src/main/resources/static 디렉토리의 index.html 파일을 읽어 클라이언트에 응답
- Request Line에서 path 분리
- path에 해당하는 파일 읽어 응답
- HTTP Request 내용 출력
- 서버로 들어오는 HTTP Request의 내용을 읽고 적절하게 파싱해서 로거(log.debug)를 이용해 출력
- nio 의존성 제거
- java.nio.file.Files 및 Paths 클래스 사용 제거
- java.io.File을 사용하여 파일 존재 여부 확인 구현
- java.io.FileInputStream을 사용하여 파일 내용 읽기 구현
- Thread 기반 코드를 concurrent 패키지 기반으로 교체
- oop 고려 refactoring
- request와 response의 재사용을 위해 따로 클래스 제작
> week 1 - step 1:

- .idea/compiler.xml
- .idea/misc.xml
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/WebServer.java
- ExecutorService를 이용한 쓰레드풀 생성 및 요청 처리
- Uri 파싱 및 정적 html 파일 응답
- HTTP Request Header를 logger를 이용해 출력
> [FEAT] week1 웹 서버 1단계 - index.html 응답

- src/main/java/common/WebUtils.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/WebServer.java
- 응답에 동적으로 ContentType값 설정
- 대상 확장자: html, css, js, ico, png, jpg, svg
> fix: week1 2단계 - 다양한 컨텐츠 타입 지원

- .idea/compiler.xml
- .idea/misc.xml
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/WebServer.java
- 응답값에 html, css, js, ico, png, jpg 등 다양한 컨텐츠 타입 지원.
- 로그 가독성 향상
> 컨텐츠 타입 지원 추가

- .idea/encodings.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/modules/be-was-neon.test.iml
- README.md
- src/main/java/hello.java
- src/main/java/webserver/PathPar.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/WebServer.java
- src/test/java/webserver/PathParTest.java
1. Concurrent 패키지를 사용하여 threadPool 생성
2. RequestHandler에서 url파싱 로직 생성
3. nio를 안쓰고 url 매핑 구현 및 성공
4. try-with-resource 구문으로 FileInputStream 과 BufferedReaderStream에서 획득한 자원 자동으로 반납
5. Junit 테스트를 통한 path 분리 테스트 완료
> WEEK1 TASK1[index.html 응답]

- .idea/encodings.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/modules/be-was-neon.test.iml
- README.md
- src/main/java/hello.java
- src/main/java/webserver/PathPar.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/WebServer.java
- src/test/java/webserver/PathParTest.java
- src/test/java/webserver/RequestHandlerTest.java
- Switch문을 통한 Content-Type 변환
- Junit Test를 통해 Content-Type 변환 메소드 테스트
- 브라우저에 출력 성공
> [Week1 Task2] - 다양한 컨텐츠 타입 지원

- src/main/java/model/User.java
- src/main/java/webserver/ContentType.java
- src/main/java/webserver/FileContentReader.java
- src/main/java/webserver/HttpRequestParser.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/WebServer.java
- src/main/java/webserver/mapping/MappingHandler.java
- src/main/java/webserver/mapping/mapper/GetCreateUserMapper.java
- src/main/java/webserver/mapping/mapper/GetHomeMapper.java
- src/main/java/webserver/mapping/mapper/GetRegistrationMapper.java
- src/main/java/webserver/mapping/mapper/HttpMapper.java
- src/main/resources/static/registration/index.html
- src/test/java/webserver/FileContentReaderTest.java
- src/test/java/webserver/HttpRequestParserTest.java
- ReadMe 추가
- ThreadPool 수정
- Content-Type 추출 및 헤더 삽입
- Accept 사용 시 우선순위 Type 추출 불가
- StartLine 에서 Path 에서 확장자 추출
- favicon.ico 요청 시 에러 발생 및 해결
- BufferedReader 로 String 으로 읽고 Byte 반환 시 에러
- Byte [] 타입으로 파일 읽고 반환
- static 메서드 -> 싱글톤 클래스로 변경 및 의존성 주입
- RequestHandler.java 의 Request Parsing 부분 리팩토링 및 메서드 추출
- 요청 Mapping 방식 및 반환 시 Code 에 따른 매핑 설계
- 회원가입 이후 302 Redirection
> [week 1-3] 김민규 

- README.md
- src/main/java/constant/FileExtensionType.java
- src/main/java/webserver/RequestHandler.java
- Content Type 및 파일 확장자를 enum으로 관리
- 파일 확장자를 파싱하여 알맞은 Content-Type을 설정하는 기능 구현
- 관리 대상이 아닌 파일 확장자일 경우, 404 error 페이지 응답
> [FEAT] week1 웹 서버 2단계 - 다양한 컨텐츠 타입 지원

- src/main/java/util/HttpRequest.java
- src/main/java/webserver/RequestHandler.java
- src/test/java/util/HttpRequestTest.java
- src/test/java/util/HttpResponseTest.java
- 기능 추가
JongssLee/be-was-2024:step2 -> softeerbootcamp4th/be-was-2024:JongssLee
- 다양한 컨텐츠 타입 지원하도록 수정
- html뿐만 아니라 css, png, svg등 다양한 컨텐츠를 지원하도록 수정
- HTTPRequest 클래스에 content를 get하는 함수 "getContentType" 선언
- requestHandler에서는 getContentType을 사용하여 알맞은 content를 response에 넘김
- requestHandler 리팩토링
- RequestHandler의 run 함수에서 책임을 명확히하고 기능을 더 작은 단위로 나누기 위해 리팩토링 진행
- run 메서드는 createHttpRequest, createHttpResponse, handleRequest 메서드로 분리
- handleRequest 메서드는 요청 URL에 따라 handleRootRequest와 handleFileRequest 중 선택
- 각 요청 처리는 별도의 메서드(handleRootRequest, handleFileRequest, send404Response)로 분리하여 책임을 명확히 하도록 변경.
- HttpRequest 클래스에 대한 단위 테스트 추가:
- 요청 라인 파싱 (메서드, URL, HTTP 버전) 검증
- 헤더 파싱 검증
- URL 확장자에 따른 콘텐츠 타입 설정 검증
- HttpResponse 클래스에 대한 단위 테스트 추가:
- 올바른 헤더와 본문을 포함한 200 OK 응답 검증
- 올바른 헤더와 본문을 포함한 404 Not …
> 이종서: step2 - 다양한 컨텐츠 타입 지원

- .idea/modules.xml
- .idea/modules/be-was-neon.test.iml
- src/main/java/util/FileUtil.java
- src/main/java/webserver/DynamicRequestProcess.java
- src/main/java/webserver/HttpRequestParser.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/UriMapper.java
- src/test/java/util/FileUtilTest.java
- src/test/java/webserver/DynamicRequestProcessTest.java
- src/test/java/webserver/HttpRequestParserTest.java
- src/test/java/webserver/RequestHandlerTest.java
- src/test/java/webserver/UriMapperTest.java
- src/test/resources/test.html
- src/test/resources/test.txt
> 1주차 웹서버 과제 리팩토링 및 테스트 코드 추가, 사소한 기능 추가

- .gitignore
- gradlew.bat
- src/main/java/common/FileUtils.java
- src/main/java/common/JsonBuilder.java
- src/main/java/common/WebUtils.java
- src/main/java/file/ViewFile.java
- src/main/java/web/ContentType.java
- src/main/java/web/HttpMethod.java
- src/main/java/web/HttpRequest.java
- src/main/java/web/HttpResponse.java
- src/main/java/web/ResponseCode.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/ViewResolver.java
- src/main/java/webserver/WebAdapter.java
- src/main/java/webserver/WebServer.java
1. 기존 PR(https://github.com/softeerbootcamp4th/be-was-2024/pull/46)에 객체지향적 코드구조를 추가하였습니다. 
2. 기존 PR의 방식으로는 IO Burst의 이점조차 가져갈 수 없어(싱글스레드와 동일하게 동작합니다) 블로킹 방식으로 콜백을 기다리는 스레드를 추가했습니다.
> week1 과제 1~3 마무리 PR

- .idea/misc.xml
- .idea/vcs.xml
- README.md
- build.gradle
- src/main/java/db/Database.java
- src/main/java/model/User.java
- src/main/java/webserver/AddressHandler.java
- src/main/java/webserver/FileHandler.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/WebServer.java
- src/main/resources/static/registration/index.html
- src/test/java/model/AddressHandlerTest.java
- src/test/java/model/FileHandlerTest.java
- src/test/java/model/UserUnitTest.java
Get으로 회원가입 구현
회원가입 폼 작성을 위한 html수정
회원가입 클릭 시 회원가입 완료 메시지 및 아이디 출력
Junit를 이용한 user unit 테스트 구현
객체 리팩토링 진행
-> AddressHandler, FileHandler 추가
-> RequestHandler 수정
유닛 테스트 추가
-> AddressHandlerTest, FileHandlerTest 추가
README파일 작성
> Weekend1 3

- .gitignore
- src/main/java/data/HttpRequestMessage.java
- src/main/java/data/HttpResponseMessage.java
- src/main/java/data/RegistrationRequest.java
- src/main/java/db/Database.java
- src/main/java/db/Session.java
- src/main/java/handler/ViewHandler.java
- src/main/java/util/FileUtil.java
- src/main/java/webserver/DynamicRequestProcess.java
- src/main/java/webserver/HttpRequestParser.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/UriMapper.java
- src/main/resources/static/login/index.html
- src/main/resources/static/main/index.html
- src/main/resources/static/registration/index.html
- src/main/resources/static/user/list.html
- src/test/java/webserver/DynamicRequestProcessTest.java
- src/test/java/webserver/HttpRequestParserTest.java
- src/test/java/webserver/UriMapperTest.java
- 이미지 파일등 바이트 파일을 받을 수 있도록 Request메시지를 Byte기반으로 처리하도록 함.
- 회원가입 로직을 POST로 변경
- 코드 리팩토링
- HttpResponse메시지 추가
- 세션방식 로그인 기능 구현
- 파일 읽기 성능 개선
- 간단한 템플릿 엔진 구현
- 로그인 된 메인페이지 구현
- 로그아웃 기능 구현
- 유저목록 기능 구현
> 웹서버 2주차 과제

- build.gradle
- src/main/java/constant/HttpMethod.java
- src/main/java/constant/HttpStatus.java
- src/main/java/constant/MimeType.java
- src/main/java/dto/HttpRequest.java
- src/main/java/dto/HttpResponse.java
- src/main/java/exception/HttpRequestParsingException.java
- src/main/java/exception/InvalidHttpRequestException.java
- src/main/java/handler/Handler.java
- src/main/java/handler/HandlerManager.java
- src/main/java/model/User.java
- src/main/java/util/HttpRequestParser.java
- src/main/java/webserver/Dispatcher.java
- src/main/java/webserver/RequestHandler.java
- src/main/resources/static/register/index.html
- src/test/java/IntegrationTest.java
- src/test/java/util/HttpRequestParserTest.java
- src/test/java/webserver/RequestHandlerTest.java
- 회원가입 html 파일의 form 태그 내 method를 get에서 post로 수정
- 가입 후 http redirect를 통해 index.html로 이동하도록 구현
- GET으로 회원가입 요청 시, 404 에러 페이지를 보내도록 구현하고 테스트 코드 작성
- Dispatcher 클래스를 생성하여 RequestHandler에서 예외 응답을 보낼 때 DataOutputStream이 닫히는 문제를 해결
- HttpResponse 클래스를 생성하여 응답 생성 로직을 Handler에서 분리
> [FEAT] week1 웹 서버 4단계 - POST로 회원가입

- src/main/java/common/ResponseUtils.java
- src/main/java/common/StringUtils.java
- src/main/java/common/WebUtils.java
- src/main/java/db/SessionDatabase.java
- src/main/java/db/SessionIdMapper.java
- src/main/java/db/UserDatabase.java
- src/main/java/exception/CannotResolveRequestException.java
- src/main/java/exception/SizeNotMatchException.java
- src/main/java/facade/SessionFacade.java
- src/main/java/facade/UserFacade.java
- src/main/java/model/Cookie.java
- src/main/java/model/Session.java
- src/main/java/web/HttpRequest.java
- src/main/java/web/HttpResponse.java
- src/main/java/web/HttpSession.java
- src/main/java/web/MIME.java
- src/main/java/web/ResponseCode.java
- src/main/java/web/RestUri.java
- src/main/java/web/ViewPath.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/ViewResolver.java
- src/main/java/webserver/WebAdapter.java
- src/main/java/webserver/WebServer.java
- src/main/resources/static/index.html
- src/main/resources/static/login/index.html
- src/main/resources/static/registration/index.html
- src/test/java/user/RegistrationTest.java
- 요청/응답 body에서 String이 아닌 byte[] 사용하도록 변경
- Session, Cookie 객체 추가
- Session In-memory Database 추가
- SessionId-UserId 매핑 테이블 DB 추가
- 응답 로직에 HttpResponse객체 사용하도록 수정
- 로그아웃 기능 구현 (로그아웃 시 해당 세션쿠키 Age 만료시키는 방식)
- 로그아웃시 Session DB에서 만료된 세션 제거
- Spring Batch 등의 배치 툴로 만료 작업을 자동화하는 방식으로 디벨롭 가능
- 하드코딩 제거
> [Week2 step 1~2] POST로 회원 가입, 세션 쿠키를 이용한 로그인

- src/main/java/common/FileUtils.java
- src/main/java/common/RequestUtils.java
- src/main/java/common/ResponseUtils.java
- src/main/java/common/StringUtils.java
- src/main/java/common/WebUtils.java
- src/main/java/db/SessionDatabase.java
- src/main/java/db/SessionIdMapper.java
- src/main/java/db/UserDatabase.java
- src/main/java/exception/CannotResolveRequestException.java
- src/main/java/exception/SizeNotMatchException.java
- src/main/java/facade/SessionFacade.java
- src/main/java/facade/UserFacade.java
- src/main/java/model/Cookie.java
- src/main/java/model/Session.java
- src/main/java/web/DynamicHtmlGenerator.java
- src/main/java/web/HttpRequest.java
- src/main/java/web/HttpResponse.java
- src/main/java/web/HttpSession.java
- src/main/java/web/MIME.java
- src/main/java/web/ResponseCode.java
- src/main/java/web/RestUri.java
- src/main/java/web/ViewPath.java
- src/main/java/webserver/RequestHandler.java
- src/main/java/webserver/ViewResolver.java
- src/main/java/webserver/WebAdapter.java
- src/main/java/webserver/WebServer.java
- src/main/resources/static/index.html
- src/main/resources/static/login/index.html
- src/main/resources/static/registration/index.html
- src/test/java/user/RegistrationTest.java
- 동적 페이징 기능 추가
- 파일을 String으로 받아서 일부 문자열을 replace하는 방법 채택
- 메인 페이지 로그인/비로그인 분기
- 유저리스트 페이지 접근시 인증된 접근인지 체크
> [Week2/feature3] 동적 페이징 기능 추가

- .idea/compiler.xml
- .idea/misc.xml
- .idea/sqldialects.xml
- build.gradle
- src/main/java/builder/CookieBodyBuilder.java
- src/main/java/builder/HtmlBuilder.java
- src/main/java/builder/NoneCookieBodyBuilder.java
- src/main/java/db/PostDatabase.java
- src/main/java/db/UserDatabase.java
- src/main/java/distributor/GetDistributor.java
- src/main/java/distributor/PostDistributor.java
- src/main/java/model/Post.java
- src/main/java/model/User.java
- src/main/java/model/ViewData.java
- src/main/java/processor/PostProcessor.java
- src/main/java/processor/ResponseProcessor.java
- src/main/java/processor/UserProcessor.java
- src/main/java/utils/CookieUtil.java
- src/main/java/utils/ResourceUtil.java
- src/main/java/webserver/Request.java
- src/main/resources/static/comment/index.html
- src/main/resources/static/index.html
- src/main/resources/static/main/index.html
- src/main/resources/static/post/index.html
- src/main/resources/static/post/list.html
- src/main/resources/static/user/list.html
- src/main/resources/static/write/index.html
- src/test/java/builder/HtmlBuilderTest.java
- 글 목록으로 이동하기 위한 버튼 추가
- 사용자 목록으로 이동하기 위한 버튼 추가
- h2 데이터베이스 연동 및 테이블 생성
- 글 작성 기능 추가
- 글 보여주는 html 추가
- 사용자 id와 글 제목을 이용해 글의 제목과 내용 보여줄 수 있도록 구현
- 이미지를 보여줄 수 있는 image_placeholder 추가. 추후 동적으로 이미지 보여주도록 구현 예정
> Feature7-1

- .gitignore
- build.gradle
- src/main/java/db/Database.java
- src/main/java/model/Article.java
- src/main/java/processor/ArticleRequestProcessor.java
- src/main/java/processor/RequestProcessor.java
- src/main/java/processor/RootRequestProcessor.java
- src/main/java/processor/UserRequestProcessor.java
- src/main/java/utils/FileUtils.java
- src/main/java/utils/JDBCUtils.java
- src/main/java/webserver/RequestDispatcher.java
- src/main/java/webserver/RequestInfo.java
- src/main/resources/static/article/index.html
- src/main/resources/static/index.html
- 글 및 이미지 업로드 기능
- 메인 화면에서 작성된 글 확인 
- 이전글 / 다음글 이동\
- 세션을 제외한 인메모리 DB를 H2 DB로 변경
> WAS 3주차 - 7단계

- README.md
- src/main/java/builder/HtmlBuilder.java
- src/main/java/db/PostDatabase.java
- src/main/java/enums/MimeType.java
- src/main/java/model/FileData.java
- src/main/java/model/Post.java
- src/main/java/processor/PostProcessor.java
- src/main/java/utils/ResourceUtil.java
- src/main/java/webserver/Request.java
- src/main/resources/static/index.html
- src/main/resources/static/write/index.html
- 이미지를 업로드하는 기능 추가
- 데이터베이스 테이블에 이미지가 저장된 경로를 저장할 수 있는 column 추가
- 메인화면에서 글 목록을 직접 보여주지 않고 글 목록 링크로 들어가야 볼 수 있도록 수정
- 멀티파트 데이터를 파싱하여 이미지를 데이터베이스에 저장하는 기능 추가
- 글에서 이미지를 로드하여 보여주는 기능 추가
> Feature7 2
